### ISSUE TITLE
Github Token is in github.js

### ISSUE THREAD

**Issue by agundy** [rcos/stats#31]
@seveibar you need to reset your account token and remove it from the github.js file

**Comment by seveibar** [comment]
fixed in #32

**Comment by zmike808** [comment]
Just a heads up, token is still easily visible in commit history. May want to just invalidate it, or purge commit history or both.

**Comment by aeksco** [comment]
Resolved by #32 - @seveibar I'm sure you've deactivated this access token by now :)
